### ISSUE TITLE
node not working anymore in latest HassOS / NodeRED setup

### ISSUE THREAD

**Issue by ojkaas** [hobbyquaker/node-red-contrib-lgtv#27]
Hi,

I am running the following setup:

Add-on version: 7.1.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 242

And I have a hunch that because of the bumped node version this node is not compiling anymore, but I do not have enough knowledge about how all this stuff works together so putting this here.

After I updated yesterday and trying to startup node-red with this node added I get the following error:

> bufferutil@4.0.1 install /opt/node_modules/bufferutil
> node-gyp-build
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 4.19.127-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/bufferutil
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T07_10_39_741Z-debug.log
[09:10:39] FATAL: Failed to install a specified npm package
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...

**Comment by gmarquezp** [comment]
On nodered config addon add system_packages: [make]

**Comment by gmarquezp** [comment]
Fix found:
you need to add this packages on the config of the addon:

```
system_packages:
  - make
  - gcc
  - g++
  - libc-dev
```

**Comment by Rtamagnini** [comment]
> Fix found:
> you need to add this packages on the config of the addon:
> 
> ```
> system_packages:
>   - make
>   - gcc
>   - g++
>   - libc-dev
> ```

What addon ?


I put it here and it didn't work: 

  base_url: !secret duckdns
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  system_packages:
    - make
    - gcc
    - g++
    - libc-dev

**Comment by gmarquezp** [comment]
Go to Supervisor / select node red add-on / go to configuration on the upper part of the screen. the add the packages on the system_packages section of the configuration and click save.

**Comment by hobbyquaker** [comment]
[node-red-contrib-lgtv 2.0.0](https://github.com/hobbyquaker/node-red-contrib-lgtv/releases/tag/v2.0.0) is released (npm `latest`); it needs Node-RED >= 4 and Node.js >= 20.19 (^20.19 || ^22.12 || >=24), see the [changelog](https://github.com/hobbyquaker/node-red-contrib-lgtv/blob/master/CHANGELOG.md).

The install failure is the native build of `bufferutil`/`utf-8-validate` pulled in by the old `websocket` package (it needs make/gcc/python on the host). 2.0 uses [lgtv2 2.0](https://github.com/hobbyquaker/lgtv2) with the pure-JS `ws` transport, so nothing is compiled during install any more - on a Raspberry Pi, in Docker or in the Home Assistant add-on. Please update to 2.0.0 and reopen if the install still fails.

---
_This comment was written by an AI agent (Claude Code) on behalf of @hobbyquaker._
