### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by Rtamagnini** [hobbyquaker/node-red-contrib-lgtv#35]
Hello, i have hassio in an rpi3.

when installing I'm getting this error:
getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)

what should I do to install lgtv?

2020-12-02T19:47:00.345Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-lgtv@1.1.0
2020-12-02T19:47:13.342Z [out] 
2020-12-02T19:47:13.342Z [out] > bufferutil@4.0.2 install /config/node-red/node_modules/bufferutil
2020-12-02T19:47:13.342Z [out] > node-gyp-build
2020-12-02T19:47:13.342Z [out] 
2020-12-02T19:47:18.900Z [err] gyp
2020-12-02T19:47:18.902Z [err]  
2020-12-02T19:47:18.903Z [err] ERR! build error 
2020-12-02T19:47:18.905Z [err] gyp
2020-12-02T19:47:18.906Z [err]  ERR! 
2020-12-02T19:47:18.906Z [err] stack Error: not found: make
2020-12-02T19:47:18.906Z [err] gyp ERR! 
2020-12-02T19:47:18.907Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-02T19:47:18.907Z [err] gyp ERR!
2020-12-02T19:47:18.907Z [err]  stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-02T19:47:18.908Z [err] gyp ERR!
2020-12-02T19:47:18.908Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-02T19:47:18.908Z [err] gyp ERR! 
2020-12-02T19:47:18.908Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-02T19:47:18.908Z [err] gyp ERR! 
2020-12-02T19:47:18.909Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-02T19:47:18.909Z [err] gyp
2020-12-02T19:47:18.909Z [err]  ERR! 
2020-12-02T19:47:18.909Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-02T19:47:18.909Z [err] gyp 
2020-12-02T19:47:18.910Z [err] ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-02T19:47:18.911Z [err] gyp
2020-12-02T19:47:18.911Z [err]  ERR! System Linux 4.19.127-v8
2020-12-02T19:47:18.912Z [err] gyp ERR! command
2020-12-02T19:47:18.912Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-12-02T19:47:18.912Z [err] gyp
2020-12-02T19:47:18.912Z [err]  ERR! cwd /config/node-red/node_modules/bufferutil
2020-12-02T19:47:18.912Z [err] gyp 
2020-12-02T19:47:18.913Z [err] ERR! node -v v12.18.4
2020-12-02T19:47:18.913Z [err] gyp 
2020-12-02T19:47:18.913Z [err] ERR! node-gyp -v v5.1.0
2020-12-02T19:47:18.913Z [err] gyp ERR!
2020-12-02T19:47:18.914Z [err]  not ok 
2020-12-02T19:47:19.394Z [err] npm
2020-12-02T19:47:19.394Z [err]  ERR! code ELIFECYCLE
2020-12-02T19:47:19.395Z [err] npm 
2020-12-02T19:47:19.395Z [err] ERR! errno 1
2020-12-02T19:47:19.412Z [err] npm
2020-12-02T19:47:19.412Z [err]  ERR! bufferutil@4.0.2 install: `node-gyp-build`
2020-12-02T19:47:19.412Z [err] npm ERR! Exit status 1
2020-12-02T19:47:19.412Z [err] npm ERR!
2020-12-02T19:47:19.413Z [err]  
2020-12-02T19:47:19.413Z [err] npm ERR!
2020-12-02T19:47:19.413Z [err]  Failed at the bufferutil@4.0.2 install script.
2020-12-02T19:47:19.413Z [err] npm 
2020-12-02T19:47:19.413Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-02T19:47:19.449Z [err] 
2020-12-02T19:47:19.451Z [err] npm ERR!
2020-12-02T19:47:19.452Z [err]  A complete log of this run can be found in:
2020-12-02T19:47:19.452Z [err] npm ERR!     /root/.npm/_logs/2020-12-02T19_47_19_425Z-debug.log

**Comment by hobbyquaker** [comment]
[node-red-contrib-lgtv 2.0.0](https://github.com/hobbyquaker/node-red-contrib-lgtv/releases/tag/v2.0.0) is released (npm `latest`); it needs Node-RED >= 4 and Node.js >= 20.19 (^20.19 || ^22.12 || >=24), see the [changelog](https://github.com/hobbyquaker/node-red-contrib-lgtv/blob/master/CHANGELOG.md).

The install failure is the native build of `bufferutil`/`utf-8-validate` pulled in by the old `websocket` package (it needs make/gcc/python on the host). 2.0 uses [lgtv2 2.0](https://github.com/hobbyquaker/lgtv2) with the pure-JS `ws` transport, so nothing is compiled during install any more - on a Raspberry Pi, in Docker or in the Home Assistant add-on. Please update to 2.0.0 and reopen if the install still fails.

---
_This comment was written by an AI agent (Claude Code) on behalf of @hobbyquaker._
