### ISSUE TITLE
ERROR DOWNLOAD

### ISSUE THREAD

**Issue by zeroincondotta** [hobbyquaker/node-red-contrib-lgtv#37]
Failed to install: node-red-contrib-lgtv

Install failed

2021-01-11T11:02:06.939Z Install : node-red-contrib-lgtv 1.1.0

2021-01-11T11:02:06.360Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-lgtv@1.1.0
2021-01-11T11:02:12.843Z [out] 
2021-01-11T11:02:12.843Z [out] > bufferutil@4.0.3 install /config/node-red/node_modules/bufferutil
2021-01-11T11:02:12.843Z [out] > node-gyp-build
2021-01-11T11:02:12.843Z [out] 
2021-01-11T11:02:15.123Z [err] gyp
2021-01-11T11:02:15.124Z [err]  
2021-01-11T11:02:15.124Z [err] ERR! build error 
2021-01-11T11:02:15.126Z [err] gyp 
2021-01-11T11:02:15.126Z [err] ERR! 
2021-01-11T11:02:15.126Z [err] stack
2021-01-11T11:02:15.126Z [err]  Error: not found: make
2021-01-11T11:02:15.126Z [err] gyp ERR!
2021-01-11T11:02:15.126Z [err]  
2021-01-11T11:02:15.126Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-01-11T11:02:15.126Z [err] gyp
2021-01-11T11:02:15.126Z [err]  ERR!
2021-01-11T11:02:15.126Z [err]  stack
2021-01-11T11:02:15.126Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-01-11T11:02:15.127Z [err] gyp ERR!
2021-01-11T11:02:15.127Z [err]  stack
2021-01-11T11:02:15.127Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-01-11T11:02:15.127Z [err] gyp 
2021-01-11T11:02:15.127Z [err] ERR! stack
2021-01-11T11:02:15.127Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-01-11T11:02:15.127Z [err] gyp
2021-01-11T11:02:15.127Z [err]  ERR! 
2021-01-11T11:02:15.127Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-01-11T11:02:15.127Z [err] gyp
2021-01-11T11:02:15.127Z [err]  ERR!
2021-01-11T11:02:15.127Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-01-11T11:02:15.127Z [err] gyp ERR!
2021-01-11T11:02:15.128Z [err]  stack     at FSReqCallback.oncomplete (fs.js:168:21)
2021-01-11T11:02:15.128Z [err] gyp
2021-01-11T11:02:15.128Z [err]  ERR! System Linux 5.4.79-v8
2021-01-11T11:02:15.129Z [err] gyp
2021-01-11T11:02:15.129Z [err]  ERR! command
2021-01-11T11:02:15.129Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-01-11T11:02:15.129Z [err] gyp
2021-01-11T11:02:15.129Z [err]  ERR! cwd
2021-01-11T11:02:15.129Z [err]  /config/node-red/node_modules/bufferutil
2021-01-11T11:02:15.129Z [err] gyp
2021-01-11T11:02:15.129Z [err]  ERR! 
2021-01-11T11:02:15.129Z [err] node -v v12.18.4
2021-01-11T11:02:15.129Z [err] gyp ERR!
2021-01-11T11:02:15.129Z [err]  node-gyp -v v5.1.0
2021-01-11T11:02:15.130Z [err] gyp ERR!
2021-01-11T11:02:15.130Z [err]  not ok 
2021-01-11T11:02:15.355Z [err] npm 
2021-01-11T11:02:15.355Z [err] ERR! code ELIFECYCLE
2021-01-11T11:02:15.355Z [err] npm ERR!
2021-01-11T11:02:15.355Z [err]  errno 1
2021-01-11T11:02:15.365Z [err] npm 
2021-01-11T11:02:15.365Z [err] ERR! bufferutil@4.0.3 install: `node-gyp-build`
2021-01-11T11:02:15.365Z [err] npm ERR! Exit status 1
2021-01-11T11:02:15.365Z [err] npm
2021-01-11T11:02:15.365Z [err]  ERR!
2021-01-11T11:02:15.366Z [err]  
2021-01-11T11:02:15.366Z [err] npm 
2021-01-11T11:02:15.366Z [err] ERR! Failed at the bufferutil@4.0.3 install script.
2021-01-11T11:02:15.366Z [err] npm ERR!
2021-01-11T11:02:15.366Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2021-01-11T11:02:15.385Z [err] 
2021-01-11T11:02:15.385Z [err] npm 
2021-01-11T11:02:15.385Z [err] ERR! A complete log of this run can be found in:
2021-01-11T11:02:15.385Z [err] npm ERR!
2021-01-11T11:02:15.386Z [err]      /root/.npm/_logs/2021-01-11T11_02_15_371Z-debug.log
2021-01-11T11:02:15.407Z rc=1

**Comment by hobbyquaker** [comment]
[node-red-contrib-lgtv 2.0.0](https://github.com/hobbyquaker/node-red-contrib-lgtv/releases/tag/v2.0.0) is released (npm `latest`); it needs Node-RED >= 4 and Node.js >= 20.19 (^20.19 || ^22.12 || >=24), see the [changelog](https://github.com/hobbyquaker/node-red-contrib-lgtv/blob/master/CHANGELOG.md).

The install failure is the native build of `bufferutil`/`utf-8-validate` pulled in by the old `websocket` package (it needs make/gcc/python on the host). 2.0 uses [lgtv2 2.0](https://github.com/hobbyquaker/lgtv2) with the pure-JS `ws` transport, so nothing is compiled during install any more - on a Raspberry Pi, in Docker or in the Home Assistant add-on. Please update to 2.0.0 and reopen if the install still fails.

---
_This comment was written by an AI agent (Claude Code) on behalf of @hobbyquaker._
