### ISSUE TITLE
Crashes on node red v2

### ISSUE THREAD

**Issue by dahlheim2** [hobbyquaker/node-red-contrib-lgtv#45]
only able to configure lgtv on node red version 1.0.  tried v2.0 with node.js v10,12 and 14 all crash node red.

**Comment by nodoubtman** [comment]
Same here.

**Comment by dahlheim2** [comment]
such a useful contrib though, thank you developer!  it has been essential to my system for years.  now i have it running on a separate RPi with node-red 1.0 running on it and the "main" system running node-red v2 just communicates with it that way.

**Comment by antoniocarlospp** [comment]
> only able to configure lgtv on node red version 1.0. tried v2.0 with node.js v10,12 and 14 all crash node red.

Hi! By crash you mean losing connection to the server? I'm using Node Red for the very first time and everytime I type my IP and click deploy I lose connection.

**Comment by dahlheim2** [comment]
Well, if you're like me then you're losing connection with node red design and dashboard because node red itself is crashing and restarting repeatedly. I can stop that by deleting the lgtv configuration.

**Comment by nodoubtman** [comment]
Node-red crash and i have a message telling me :
BUS ERROR...
nodered.service: Main process exited, code=killed, status=7/BUS
i dont kno where's coming from?

Can you help?
Thank You.
Marc.

**Comment by nodoubtman** [comment]
I created a nodejs webserver on my raspberry pi 3 which solves the problem

Thanks.
Marc.

**Comment by ZeroBLYNK** [comment]
13 Nov 11:01:20 - [red] Uncaught Exception:
13 Nov 11:01:20 - [error] TypeError: Cannot read property 'indexOf' of undefined
    at Object.916a5ac29e1d2f18 (/home/pi/.node-red/node_modules/node-red-contrib-lgtv/nodes/lgtv-volume.js:19:59)
    at /home/pi/.node-red/node_modules/node-red-contrib-lgtv/nodes/lgtv-config.js:72:43
    at Array.forEach (<anonymous>)
    at LgtvConfigNode.subscriptionHandler (/home/pi/.node-red/node_modules/node-red-contrib-lgtv/nodes/lgtv-config.js:71:49)
    at Object.4142c0110007 (/home/pi/.node-red/node_modules/node-red-contrib-lgtv/nodes/lgtv-config.js:38:26)
    at WebSocketConnection.<anonymous> (/home/pi/.node-red/node_modules/lgtv2/index.js:149:48)
    at WebSocketConnection.emit (events.js:314:20)
    at WebSocketConnection.processFrame (/home/pi/.node-red/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/pi/.node-red/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.



https://github.com/node-red/node-red.github.io/blob/a9c2f1c1630841aa4ba427b2b49b1757985a0f18/docs/user-guide/handling-errors.md#uncaughtexception-errors

_Attempting to resume normally after an uncaught exception can be similar to pulling out the power cord when upgrading a computer. Nine out of ten times, nothing happens. But the tenth time, the system becomes corrupted._

**Comment by fabiojrsantos** [comment]
same here, i can't install the node in NR v2.

**Comment by hobbyquaker** [comment]
[node-red-contrib-lgtv 2.0.0](https://github.com/hobbyquaker/node-red-contrib-lgtv/releases/tag/v2.0.0) is released (npm `latest`); it needs Node-RED >= 4 and Node.js >= 20.19 (^20.19 || ^22.12 || >=24), see the [changelog](https://github.com/hobbyquaker/node-red-contrib-lgtv/blob/master/CHANGELOG.md).

The crash on deploy came from the volume/mute nodes assuming `res.changed` in the TV's answer, which newer firmware doesn't send (#36). Fixed in 2.0.0 via lgtv2's normalized volume payload; 2.0 is tested against Node-RED 4 and 5 on Node 22/24.

---
_This comment was written by an AI agent (Claude Code) on behalf of @hobbyquaker._
